import { Audio } from "@remotion/media";
import { AbsoluteFill, Sequence, staticFile } from "remotion";
import { PARTS, partById, type PartId } from "./edit-list.ts";
import { SCENES } from "./scenes";
import {
  BEATS_PER_BAR,
  beatsAt,
  frameAt,
  framesBetween,
  SONG_END,
  type Pos,
} from "./timing.ts";

/** Generated by `npm run music` (gitignored; rebuild it after a fresh checkout). */
export const SCORE = "music/mv.wav";

// The whole MV: every part in its bars, the score underneath from frame 0.
export const MV: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: "#0d0d0d" }}>
    {PARTS.map((part) => {
      const Scene = SCENES[part.id];
      return (
        <Sequence
          key={part.id}
          name={`${part.name} ${part.from.bar}–${part.to.bar - 1}`}
          from={frameAt(part.from)}
          durationInFrames={framesBetween(part.from, part.to)}
        >
          <Scene part={part} />
        </Sequence>
      );
    })}
    <Audio src={staticFile(SCORE)} />
  </AbsoluteFill>
);

/** One bar of what follows, so a part's preview shows its last cut (the intro's lights-out). */
const previewEnd = (id: PartId): Pos => {
  const to = partById(id).to;
  return beatsAt(to) + BEATS_PER_BAR <= beatsAt(SONG_END)
    ? { bar: to.bar + 1, beat: to.beat }
    : to;
};
export const partPreviewFrames = (id: PartId) =>
  framesBetween(partById(id).from, previewEnd(id));

// A window onto the MV: the part plus one bar after it, with the score at the right offset.
export const PartPreview: React.FC<{ part: PartId }> = ({ part }) => (
  <Sequence from={-frameAt(partById(part).from)}>
    <MV />
  </Sequence>
);
